sudo: false
language: python
python:
  - 2.7

env:
  global:
  - secure: |-
      WFqJNyPzFKCXFQnMxlbm42C6/4OO82rZXN0N7b2Zqer3PuWxbWSFsCdodsLGUib0bO
      tX+X9dFMPiQCXAUWK74v95vCoMMZEoDlh4QpsGf0oEDU/Y4CvOgnlm0YVd6s7jTZIF
      42mExSup8IwMqsHJyDTQMM/Y3irrJbNolHiDGn4=  # AWS_ACCESS_KEY_ID
  - secure: |-
      DyQVc6Lfjz7Yd3kSpXZZaN7vRoJBzK/c95N4f8wOyxNLSpgBfE+ZbDQKPzffGteuBW
      hFKdVJQADKG+UG+a0JQX88l4kt3JrWtVtaBRyrxzXHLFJaMjcLvDe0nbTeRDgEyRTu
      ji2Q0k+EVkzurHwWxECukfbYkc2u1OrtHlWnAok=  # AWS_SECRET_KEY
  - secure: |-
      ZXV+WoZ+FBO+ycRYiP8rmcMSzNb1AR212H2xGLdqHdsxatBMbs4KVJoYDl7xwaCVGH
      b8bc91A13D8DF8d/YT1MytNK/UKf5YyP6wYKeQfqFBzDjxSYxgG3apMTfFuS7lGWZx
      mmXgOgh9KY7iw/FiJN+v7se3umyuNgJ5HXenjnQ=  # INTERNAL_PYPI_PASS

install:
  - $(which echo) -e "[buildout]\nextends = buildout.d/travis.cfg" > buildout.cfg
  - make .installed.cfg
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash

script:
  - make tests
  - make docs

after_success:
  - test $TRAVIS_BRANCH == 'master' && make upload_docs

before_deploy:
  - git fetch --unshallow
  - bin/py prepare_versions_cfg.py
  - VERSIONS=$(ls versions-*.cfg)
  - curl --insecure -u niteoweb:$INTERNAL_PYPI_PASS -F ":action=file_upload" -F "content=@$VERSIONS" https://pypi.niteoweb.com

deploy:
  provider: pypi
  server: https://pypi.niteoweb.com
  user: niteoweb
  password:
    secure: k7TBVMXzRKqgt9boaAik45BOV8FHz5+rp5wHKM2/QA0MB0BK4tjHhTLi2nVyb0sQujPpFCWCvTYUx4jfbnaqN0wFakSH3kCnf/T61o3BtzOOX0ewqNdVuI0uqSBRgR2xqWtBGIz7zK5GOTOgMOgbqNETHbTXbQfLTJS9D6EHvv4=
  on:
    tags: true
    all_branches: true

notifications:
  irc:
    skip_join: true
    channels:
      - "irc.freenode.org#niteoweb"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
  slack:
    secure: Wk/ysxO1T2HC4BRo/w9CnBlHHFEO3JfFQdUCM6BeU/WcuYwnPt88QYhrnI/13zA8SLaI82Lpg3cLSBzJzvpw35eQgHJ0QN9ObVyh6hVRXDBlNkUPJdDtXHNPmBHfC/qMRwDxn8FLg9ypX+MBXmey6jffWAJ/GNKArmpH0fjtm9g=

cache:
  bundler: true
  directories:
    - /home/travis/build/niteoweb/pyramid_bimt/eggs
