language: python
python:
  - 2.7

env:
  global:
  - secure: |-
      eWQmVzpv7TqRe9PV0GyQXwZMRRRU9AKmlBLzBCt/hC5vOzvyXHZxKwdCfP25
      DuHpcHfPerDsZXurvAVw63WMcUW7isGu27Kw+wSjPv9eboBqhUOvl8T4ZH+1
      3+VGyvZoFtFv6DhIUOzvSE3xHRoMmZALm14wcUIKk/dBiFh76a8=  # COVERALLS TOKEN

install:
 - npm install jshint -g
 - $(which echo) -e "[buildout]\nextends = buildout.d/travis.cfg" > buildout.cfg
 - make .installed.cfg

script:
 - make coverage
 - bin/code-analysis

after_success:
 - pip install python-coveralls==2.4.0
 - coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#niteoweb"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
